fix pages

diff --git a/scripts/page-file-references-are-correct b/scripts/page-file-references-are-correct
--- a/scripts/page-file-references-are-correct
+++ b/scripts/page-file-references-are-correct
@@ -1,8 +1,11 @@
 #!/bin/bash
-SCRIPTPATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
+SCRIPTPATH="$(
+    cd -- "$(dirname "$0")" >/dev/null 2>&1
+    pwd -P
+)"
 CONFIGPATH=$SCRIPTPATH/../extension/src/pages.json
-PAGESCRIPTSPATH=$SCRIPTPATH/../extension/src/pages
-MANIFESTPATH=$SCRIPTPATH/../extension/src/manifest.json
+PAGESCRIPTSPATH=$SCRIPTPATH/../extension/src/entrypoints
+# MANIFESTPATH=$SCRIPTPATH/../extension/src/manifest.json
 
 for page in $(jq -r ".pages[].script" $CONFIGPATH); do
     if [[ $page = "null" ]]; then
@@ -17,12 +20,12 @@ for page in $(jq -r ".pages[].script" $CONFIGPATH); do
         exit 1
     fi
 
-    page_script_relative_path="pages/$page_basename.js"
-    jq ".web_accessible_resources" $MANIFESTPATH | grep "$page_script_relative_path" >/dev/null
+    # TODO: manifest is no longer manually created, so will need to check in a different way
+    # page_script_relative_path="$page_basename.js"
+    # jq ".web_accessible_resources" $MANIFESTPATH | grep "$page_script_relative_path" >/dev/null
 
-    if [ $? -eq 1 ]; then
-        echo "$page_script_relative_path missing from extension manifest web_accessible_resources"
-        exit 1;
-    fi
+    # if [ $? -eq 1 ]; then
+    #     echo "$page_script_relative_path missing from extension manifest web_accessible_resources"
+    #     exit 1
+    # fi
 done
-
